apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actual-budget
commonLabels:
  app.kubernetes.io/part-of: actual-budget

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - pvc.yml
  - ingress.yml

images:
  - name: ghcr.io/actualbudget/actual-server
    newTag: "23.11.0"

configMapGenerator:
  - name: actual-config
    envs:
      - config.env
