---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-scraper



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus:discovery
rules:
  - apiGroups: [ "" ]
    resources: [ services, pods, endpoints, nodes ]
    verbs: [ get, list, watch ]
  - apiGroups: [ networking.k8s.io ]
    resources: [ ingresses ]
    verbs: [ get, list, watch ]
  - apiGroups: [ discovery.k8s.io ]
    resources: [ endpointslices ]
    verbs: [ get, list, watch ]



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus:scrape
rules:
  - apiGroups: [ "" ]
    resources: [ nodes/metrics ]
    verbs: [ get ]
  - nonResourceURLs: [ /metrics ]
    verbs: [ get ]



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus:discovery
subjects:
  - kind: ServiceAccount
    name: prometheus-scraper


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-scrape
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus:scrape
subjects:
  - kind: ServiceAccount
    name: prometheus-scraper
