# networking config
ip: "{{ private_ipv4 }}"
access_ip: "{{ private_ipv4 }}"
enable_nodelocaldns: false
kube_network_plugin: kube-router

# don't use stub resolver to prevent issues with coredns.
# coredns gets this file mounted into its pod and if it contains the 127.0.0.53 stub resolver, coredns runs into a loop
systemd_resolved_file: resolv.conf

# container runtime config
container_manager: crio
crio_pids_limit: 4096

# add custom domain to generated ssl certs so that we can easily address the cluster from the outside
supplementary_addresses_in_ssl_keys: [ "{{ hostvars['k8s-api'].public_dns }}" ]

# disable kubespray on-host proxy to the api server because we don't need it, and it's very kubespray specific and
# non-standard when compared to other kubernetes distributions
loadbalancer_apiserver_localhost: false
