apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  selector:
    matchLabels: {}  # gets populated via kustomization
  template:
    metadata:
      labels: {}
    spec:
      serviceAccountName: cert-manager-webhook-hetzner
      containers:
        - name: cert-manager-webhook-hetzner
          image: docker.io/mecodia/cert-manager-webhook-hetzner
          imagePullPolicy: Always
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "dns.hetzner.cloud"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-hetzner-webhook-tls