apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  selector: {}  # gets populated via kustomization
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
