apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels: &labels
    app.kubernetes.io/name: website
    app.kubernetes.io/component: website-server
spec:
  replicas: 3
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: homepage
          image: ghcr.io/ftsell/homepage
          envFrom:
            - configMapRef:
                name: website
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              port: http
              httpHeaders:
                - name: Host
                  value: ftsell.de
