- tags: [ storage-box, shared-storage-mount, k8s ]
  block:
    - name: create local storage group
      become: true
      notify: add ftsell to storage-box group
      group:
        name: storage-box
        gid: 2000

    - name: create local storage user
      become: true
      user:
        name: storage-box
        uid: 2000
        group: storage-box
        home: /opt/k8s/storage-box
        create_home: false
        password_lock: true
        shell: /usr/sbin/nologin

    - name: uninstall cifs
      become: true
      apt:
        name: cifs-utils
        state: absent
        purge: true

    - name: install nfs-client
      become: true
      apt:
        name: nfs-client

    - name: configure fstab entry for auto-mounting
      become: true
      mount:
        src: "{{ hostvars['storage'].private_ipv4 }}:/srv/storage-box-virt"
        path: /srv/shared-storage
        fstype: nfs
        opts: defaults
        state: mounted

    - name: configure setuid/setgid bits on storage-box mount
      become: true
      file:
        path: /srv/shared-storage
        mode: u+s,g+s
