# general
node_labels: "{{ labels }}"

# networking config
enable_nodelocaldns: false
kube_proxy_strict_arp: true
kube_network_plugin: calico

# container runtime config
container_manager: crio
crio_pids_limit: 4096
crio_registries:
  - prefix: docker.io
    insecure: false
    blocked: false
    location: registry-1.docker.io
    unqualified: true

# add custom domain to generated ssl certs so that we can easily address the cluster from the outside
supplementary_addresses_in_ssl_keys: [ "{{ hostvars['main'].public_dns }}" ]

# disable kubespray on-host proxy to the api server because we don't need it, and it's very kubespray specific and
# non-standard when compared to other kubernetes distributions
loadbalancer_apiserver_localhost: false
