keys: &keys
  - &ftsell "age19h7xtfmt3py3ydgl8d8fgh8uakxqxjr74flrxev3pgmvvx94kvtq5d932d"
  - &vpn-srv "age13jcav0647guw6pr0f74gkjc06x9j5ensk9ck27dlkkafddsv0u5qqvzn65"
  - &mail-srv "age1ayrlyw9c9mwumujrvx7x3s30a42emn9k2tf9v2kw2vkcx70fvf5sj63fe6"
  - &hosting-srv "age1pzkr2kwn43cc694szra4rr9wqh63c32aqpz3vkr9at7qx294l5wsusj7s2"
  - &k8s-worker1-srv "age1g2uxex88r5fya0lgjqthp0tekalz6hq3fc8m8hhnwr36q5ylafaqcnt2hq"
  - &fluxcd "age19es5hdfpqhwrz7l6lm4a56kgftmwd2ek7nxfpw2maqzpgt4yt5aq89d4fc"
creation_rules:
  # per-host secrets
  - path_regex: "data/secrets/vpn.yml"
    key_groups:
      - age: [ *ftsell, *vpn-srv ]

  - path_regex: "data/secrets/mail.yml"
    key_groups:
      - age: [ *ftsell, *mail-srv ]

  - path_regex: "data/secrets/k8s-worker1.yml"
    key_groups:
      - age: [ *ftsell, *k8s-worker1-srv ]
      
  - path_regex: "data/secrets/hosting.yml"
    key_groups:
      - age: [ *ftsell, *hosting-srv ]
  
  # generic secrets
  - path_regex: "data/secrets/.+.yml"
    key_groups:
      - age: [ *ftsell ]
  - path_regex: "dotfiles/.+\\.secret\\..+"
    key_groups:
      - age: [ *ftsell ]
  
  # kubernetes
  - path_regex: "k8s/(.+\\.secret\\.yml)"
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age: [ *ftsell, *fluxcd ]
  - path_regex: "k8s/(.+\\.secret\\..+)"
    key_groups:
      - age: [ *ftsell, *fluxcd ]
