keys: &keys
  - &ftsell "age19h7xtfmt3py3ydgl8d8fgh8uakxqxjr74flrxev3pgmvvx94kvtq5d932d"
  - &vpn-srv "age13jcav0647guw6pr0f74gkjc06x9j5ensk9ck27dlkkafddsv0u5qqvzn65"
  - &main-srv "age16v8l42yfmdkn6j3v40ggx3axqwxw3euu4ydzlm0erl0zgjdp9yxstglejq"
  - &mail-srv "age1j6u4zps7zwul7dh308a5m702mq2p28xvwhuj326x09yqz46q2q9qclhlc0"
  - &hosting-srv "age1pzkr2kwn43cc694szra4rr9wqh63c32aqpz3vkr9at7qx294l5wsusj7s2"
  - &fluxcd "age19es5hdfpqhwrz7l6lm4a56kgftmwd2ek7nxfpw2maqzpgt4yt5aq89d4fc"
creation_rules:
  # per-host secrets
  - path_regex: "data/secrets/vpn.yml"
    key_groups:
      - age: [ *ftsell, *vpn-srv ]
  - path_regex: "data/secrets/mail.yml"
    key_groups:
      - age: [ *ftsell, *mail-srv ]
  - path_regex: "data/secrets/main.yml"
    key_groups:
      - age: [ *ftsell, *main-srv ]
  - path_regex: "data/secrets/hosting.yml"
    key_groups:
      - age: [ *ftsell, *hosting-srv ]
  
  # generic secrets
  - path_regex: "data/secrets/.+.yml"
    key_groups:
      - age: [ *ftsell ]
  - path_regex: "dotfiles/.+\\.secret\\..+"
    key_groups:
      - age: [ *ftsell ]
  
  # kubernetes
  - path_regex: "k8s/(.+\\.secret\\.yml)"
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age: [ *ftsell, *fluxcd ]
  - path_regex: "k8s/(.+\\.secret\\..+)"
    key_groups:
      - age: [ *ftsell, *fluxcd ]
