- name: Configure dyndns via ddclient
  tags: [ddclient, dyndns, dyndns_setter]
  block:

    - name: Install ddclient
      become: true
      ansible.builtin.apt:
        name: [ddclient]

    - name: Configure ddclient
      become: true
      notify: Restart ddclient
      ansible.builtin.template:
        src: ddclient.conf
        dest: /etc/ddclient.conf
        owner: root
        group: root
        mode: u=rw,g=,o=

    - name: Ensure ddclient daemon is running and enabled
      become: true
      ansible.builtin.systemd:
        name: ddclient.service
        state: started
        enabled: true
