systemd_networkd_configs:
  10-eth0.network: |
    [Match]
    Name=eth0

    [Network]
    DHCP=yes
    Address={{ ipv4 }}/32
    Address={{ ipv6 }}/96
    Address={{ lookup("community.dns.lookup", "cv.ftsell.de", type="AAAA") }}
    Gateway=fe80::1
