expected_dist: debian
expected_dist_version: 12

icinga_node_fqdn: main.srv.ftsell.de

systemd_networkd_configs:
  10-eth0.network: |
    [Match]
    Name=enp1s0

    [Network]
    DHCP=yes
    Address={{ ipv4 }}/32
    Address={{ ipv6 }}/96
    Address={{ lookup("community.dns.lookup", "cv.ftsell.de", type="AAAA") }}
    Gateway=fe80::1
