monitored_icmp_targets:
  - "monitoring.srv.ftsell.de"
  - "main.srv.ftsell.de"
  - "vpn.srv.ftsell.de"

monitored_http_targets:
  - "https://ftsell.de"
  - "https://finn-thorben.me"
  - "https://argocd.ftsell.de"
  - "https://auth.ftsell.de"
  - "https://budget.ftsell.de"
  - "https://cloud.ftsell.de"
  - "https://git.ftsell.de"
  - "https://kino.timonengelke.de"

monitored_smtp_targets:
  - "mail.ftsell.de:25"
  - "mail.ftsell.de:587"

monitored_imap_targets:
  - "mail.ftsell.de:993"
