apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  labels: &labels
    app.kubernetes.io/name: postgres-exporter
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter
          envFrom:
            - configMapRef:
                name: postgres-exporter
            - secretRef:
                name: postgres-exporter
          ports:
            - name: metrics
              containerPort: 9187
