apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  labels: &labels
    app.kubernetes.io/name: postgres-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  selector: *labels
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
