apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dev@ftsell.de
    privateKeySecretRef:
      name: letsencrypt-account-key

    solvers:
      - dns01:
          webhook:
            groupName: acme.ftsell.de
            solverName: hetzner
            config:
              secretName: hetzner-secret
              apiUrl: https://dns.hetzner.com/api/v1
