apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.2/cert-manager.yaml
  - ./hetzner-webhook
  - http-issuer.yml
  - dns-issuer.secret.yml

images:
  - name: docker.io/mecodia/cert-manager-webhook-hetzner
    newTag: "0.3.0"
