apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.1/cert-manager.yaml
  - hetzner-webhook.yml
  - issuers.yml

secretGenerators:
  - name: hetzner-secret
    options:
      disableNameSuffixHash: true
    files:
      - "api-key=hetzner-api-key.secret.txt"
