---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main
  namespace: metallb-system
spec:
  autoAssign: true
  addresses:
    - 116.202.6.114/32
    - 2a01:4f8:c17:24e4:affe::0/128

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mail
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
    - 116.202.0.235/32
    - 2a01:4f8:c17:24e4:affe::1/128
