apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-advertisement
  namespace: metallb-system
spec:
  nodeSelectors:
    - matchLabels:
        ftsell.de/purpose: load_balancer
  interfaces:
    - eth0
