apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels: &labels
    app.kubernetes.io/name: node-exporter
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      hostNetwork: true
      hostPID: true
      volumes:
        - name: host
          hostPath:
            path: /
        - name: dbus
          hostPath:
            path: /var/run/dbus
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter
          args:
            - "--path.rootfs=/host"
            - "--collector.logind"
            - "--collector.lnstat"
            - "--collector.processes"
            - "--collector.systemd"
            - "--collector.tcpstat"
            - "--collector.mountstats"
          securityContext:
            privileged: true
          volumeMounts:
            - name: host
              mountPath: /host
              readOnly: true
            - name: dbus
              mountPath: /var/run/dbus
              readOnly: true
          ports:
            - name: metrics
              containerPort: 9100
          livenessProbe:
            httpGet:
              port: metrics
              path: /
