apiVersion: apps/v1
kind: Deployment
metadata:
  name: vip-tracerouter
  labels: &labels
    app.kubernetes.io/name: vip_tracerouter
spec:
  replicas: 1 # HA is not supported
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      nodeName: main
      hostNetwork: true
      containers:
        - name: vip-tracerouter
          image: ghcr.io/ftsell/vip_tracerouter
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: cv6-vip
          args:
            - "--net=$(NETWORK)"
            - "--nhosts=$(N_HOSTS)"
            - "--iface=$(IFACE_NAME)"
