apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cv6-vip
commonLabels:
  app.kubernetes.io/part-of: cv6-vip

resources:
  - namespace.yml
  - deployment.yml

configMapGenerator:
  - name: cv6-vip
    envs:
      - config.env
