apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
commonLabels:
  app.kubernetes.io/part-of: ftsell-de-homepage

resources:
  - namespace.yml
  - ingress.yml

  - website/deployment.yml
  - website/service.yml

  - riddles/deployment.yml
  - riddles/service.yml

  - pixelflut/deployment.yml
  - pixelflut/service.yml
  - pixelflut/storage.yml

configMapGenerator:
  - name: pixelflut
    literals:
      - WIDTH=800
      - HEIGHT=600

  - name: website-riddles
    envs:
      - configs/riddles.secret.env
