enable_ip_forwarding: true

private_iface_name: enp7s0

# this is only the basic network config to make the server reachable via its public ip addresses
# the specific router routing is configured via its own role and not via the generic systemd-networkd configs
systemd_networkd_configs:
  10-eth0.network: |
    [Match]
    Name=eth0
    [Network]
    DHCP=yes
    Address={{ public_ipv4 }}/32
    IPv4ProxyARP=true

  20-private-iface.network: |
    [Match]
    Name={{ private_iface_name }}
    [Network]
    DHCP=yes
