apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ldjam-highscores
commonLabels:
  app.kubernetes.io/name: ldjam-highscores

resources:
  - manifests/namespace.yml
  - manifests/deployment.yml
  - manifests/service.yml
  - manifests/ingress.yml

secretGenerator:
  - name: highscores-server-config
    envs:
      - config.secret.env
