apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage
commonLabels:
  app.kubernetes.io/part-of: local-path-provisioner

resources:
  - namespace.yml
  - rbac.yml
  - shared-storage-deployment.yml
  - shared-storage-storage-class.yml
  - node-local-deployment.yml
  - node-local-storage-class.yml

images:
  - name: rancher/local-path-provisioner
    newTag: "v0.0.24"

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: shared-storage-config
    files:
      - config.json=shared-storage-config.json
      - helperPod.yaml=upstream-config/helper-pod.yml
      - setup=upstream-config/setup.sh
      - teardown=upstream-config/teardown.sh
  - name: node-local-config
    files:
      - config.json=node-local-config.json
      - helperPod.yaml=upstream-config/helper-pod.yml
      - setup=upstream-config/setup.sh
      - teardown=upstream-config/teardown.sh
