apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage

resources:
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.24

patches:
  - target:
      group: storage.k8s.io
      kind: StorageClass
      name: local-path
    path: storage-class.patch.yml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: local-path-config
    namespace: local-path-storage
    behavior: merge
    files:
      - config.json
