- name: Create zone directory
  tags: [icinga_zones]
  become: true
  ansible.builtin.file:
    path: /etc/icinga2/zones.d/{{ zone_definition.zone_name }}
    state: directory
    owner: nagios
    group: nagios
    mode: u=rwx,g=rx,o=

- name: Configure zone
  tags: [icinga_zones]
  become: true
  notify: Restart icinga2
  with_items: "{{ zone_definition.zone_files | dict2items(key_name='file_name', value_name='file_content') }}"
  loop_control:
    label: "{{ zone_definition.zone_name }}->{{ item.file_name }}"
  vars:
    zone_name: "{{ zone_definition.zone_name }}"
    file_name: "{{ item.file_name }}"
    file_content: "{{ item.file_content }}"
  ansible.builtin.template:
    src: zone_template.j2
    dest: /etc/icinga2/zones.d/{{ zone_name }}/{{ file_name }}
    owner: nagios
    group: nagios
    mode: u=rw,g=r,o=

