- name: Setup Icinga2 Node
  tags: [ monitoring, monitoring_server, icinga_node, icinga, icinga2 ]
  block:
    - ansible.builtin.import_tasks: setup_icinga_repo.yml
    - ansible.builtin.import_tasks: setup_icinga2_node.yml
    - ansible.builtin.import_tasks: setup_icingadb.yml
      when: icinga_node_icingaweb_enabled
    - ansible.builtin.import_tasks: setup_icingaweb.yml
      when: icinga_node_icingaweb_enabled
    - ansible.builtin.import_tasks: setup_webserver.yml
      when: icinga_node_icingaweb_enabled
