- name: Create apt keyring directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: add icinga2 repo key
  become: true
  get_url:
    url: "https://packages.icinga.com/icinga.key"
    dest: /etc/apt/keyrings/icinga2.asc

- name: add icinga2 repo definition
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/icinga2.asc] https://packages.icinga.com/debian icinga-{{ ansible_distribution_release}} main"

- name: update local apt repo information
  become: true
  ansible.builtin.apt:
    update_cache: true
