apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diun-data
  labels:
    app.kubernetes.io/name: diun
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1G"
