- tags: [ vpn, vpn_client, wireguard ]
  block:
    - name: install wireguard userland tools
      become: true
      package:
        name: wireguard-tools

    - name: configure vpn interface
      become: true
      notify: reconfigure vpn interface
      template:
        src: wg.conf
        dest: /etc/wireguard/{{ vpn_iface }}.conf

    - name: ensure vpn connection is started and enabled
      become: true
      systemd:
        name: wg-quick@{{ vpn_iface }}.service
        state: started
        enabled: true
