# allow these pods to be scheduled on the load balancer
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: ftsell.de/load-balancer
      effect: NoSchedule
      operator: Exists

# prefer scheduling these pods directly on the load balancer
- op: add
  path: /spec/template/spec/affinity
  value:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: ftsell.de/purpose
                operator: In
                values:
                  - load_balancer
          weight: 10

# add prometheus.io annotations for metric collections
- op: add
  path: /spec/template/metadata/annotations
  value:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
# add port definition to pod manifest
- op: add
  path: /spec/template/spec/containers/0/ports/-
  value:
    name: prometheus
    containerPort: 10254
