# change service type to load-balancer
- op: replace
  path: /spec/type
  value: LoadBalancer

# set sharing key so that the IP can be reused
- op: add
  path: /metadata/annotations
  value:
    metallb.universe.tf/allow-shared-ip: main-sharing-key

# change ip family to allow IPv6 traffic
- op: replace
  path: /spec/ipFamilyPolicy
  value: RequireDualStack
- op: add
  path: /spec/ipFamilies/-
  value: IPv6
