apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovatebot
commonLabels:
  app.kubernetes.io/part-of: renovatebot

resources:
  - cronjob.yml
  - namespace.yml

secretGenerator:
  - name: renovatebot-config
    envs:
      - config.secret.env
