apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/part-of: argocd
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.7/manifests/install.yaml
  - manifests/namespace.yml
  - manifests/ingress.yml

images:
  - name: quay.io/argoproj/argocd
    newName: ghcr.io/ftsell/argocd-git-crypt

replicas:
  - name: argocd-dex-server
    count: 0

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    path: manifests/repo-server.patch.yml

  - target:
      kind: ConfigMap
      name: argocd-cm
    path: config/config.yml

configMapGenerator:
  - name: argocd-ssh-known-hosts-cm
    behavior: replace
    files:
      - ssh_known_hosts=config/known_hosts

  - name: argocd-rbac-cm
    behavior: replace
    literals:
      - "policy.default=none"
    files:
      - "policy.csv=config/rbac_policy.csv"

  - name: argocd-cmd-params-cm
    behavior: merge
    envs:
      - config/argocd-params.env

secretGenerator:
  - name: argocd-secret
    behavior: replace
    envs:
      - config/secret.env

  - name: argocd-gpg-secret-keys
    files:
      - 019EC8A22D1A788E=config/gpg.key

  - name: argocd-ssh-key
    namespace: argocd
    files:
      - "sshPrivateKey=config/argocd.id_rsa"
