apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-config
spec:
  project: default
  source:
    repoURL: git@github.com:ftsell/finnfrastructure.git
    targetRevision: main
    path: k8s/cd-config
  destination:
    name: in-cluster
