---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: base-cluster
spec:
  description: Basic Cluster Functionality
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - git@github.com:ftsell/finnfrastructure.git



---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-apps
spec:
  description: Cluster and utility apps
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - git@github.com:ftsell/finnfrastructure.git



---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: user-apps
spec:
  description: End-User facing apps (what the whole cluster is actually for)
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - git@github.com:ftsell/finnfrastructure.git
