expected_dist_version: 12

icinga_node_cluster_root: "self"
icinga_node_icingaweb_enabled: true
icinga_node_icingaweb_domain: monitoring.ftsell.de
icinga_node_fqdn: monitoring.srv.ftsell.de
icinga_node_zones:
  global-templates:
    templates.conf: |
      /**
        * Provides default settings for hosts.
        * By convention, all hosts should import this template.
        */
      template Host "generic-host" {
        check_interval = 1m
        retry_interval = 30s
        check_command = "hostalive"
      }

      /**
        * Provides defaults for hosts that aren't real servers (i.e. load balancer IPs)
        */
      template Host "virtual-host" {
        check_interval = 1h
        check_command = "dummy"
      }

      /**
        * A host template valid for most normal linux servers I host
        */
      template Host "normal-server" {
        vars.apt_check_enabled = true
        vars.apt_check_notify = false
        vars.ssh_check_enabled = true
        vars.ssh_check_notify = true
        vars.systemd_check_enabled = true
        vars.systemd_check_notify = true
        vars.running_kernel_check_enabled = true
        vars.running_kernel_notify = false
      }

      /**
        * Provides default settings for services.
        * By convention all services should import this template.
        */
      template Service "generic-service" {
        max_check_attempts = 5
        check_interval = 1m
        retry_interval = 30s
      }

      /**
        * Provides default settings for users.
        * By convention all users should import this template.
        */
      template User "generic-user" {}

    services.conf: |
      apply Service "apt" to Host {
        import "generic-service"
        check_command = "apt"
        check_interval = 3h
        enable_notifications = host.vars.apt_check_notify
        assign where host.vars.apt_check_enabled
      }

      apply Service "ssh" to Host {
        import "generic-service"
        check_command = "ssh"
        enable_notifications = host.vars.ssh_check_notify
        assign where host.vars.ssh_check_enabled
      }

      apply Service "systemd" to Host {
        import "generic-service"
        check_command = "systemd"
        enable_notifications = host.vars.systemd_check_notify
        assign where host.vars.systemd_check_enabled
      }

      apply Service "running_kernel" to Host {
        import "generic-service"
        check_command = "running_kernel"
        check_interval = 5m
        enable_notifications = host.vars.running_kernel_notify
        assign where host.vars.running_kernel_check_enabled
      }

      apply Service "https://" for (domain in host.vars.websites) to Host {
        import "generic-service"
        check_command = "http"
        zone = "monitoring.srv.ftsell.de"    // perform these checks from the internet and not locally
        vars.http_vhost = domain
        vars.http_ssl = true
        vars.http_sni = true
        vars.http_onredirect = "stickyport"
        vars.http_expect = "200,302,303,401,403"
        assign where host.vars.websites
      }

      apply Service "cert-" for (domain in host.vars.websites) to Host {
        import "generic-service"
        check_command = "ssl_cert"
        zone = "monitoring.srv.ftsell.de"
        vars.ssl_cert_address = domain
        vars.ssl_cert_cn = domain
        vars.ssl_cert_sni = domain
        assign where host.vars.websites
      }

      apply Service "imaps" to Host {
        import "generic-service"
        check_command = "imap"
        vars.imap_ssl = true
        vars.imap_port = 993
        enable_notifications = host.vars.imap_notify
        assign where host.vars.imap_check_enabled
      }

      apply Service "smtp" to Host {
        import "generic-service"
        check_command = "smtp"
        vars.smtp_port = 25
        enable_notifications = host.vars.smtp_notify
        assign where host.vars.smtp_check_enabled
      }

      apply Service "submission" to Host {
        import "generic-service"
        check_command = "smtp"
        vars.smtp_port = 587
        vars.smtp_starttls = true
        enable_notifications = host.vars.submission_notify
        assign where host.vars.submission_check_enabled
      }

    notifications.conf: |
      object User "ftsell" {
        email = "admin+monitoring@ftsell.de"
        vars.telegram_id = "87082671"
      }

      template Notification "telegram-notification" {
        command = "notify-telegram"
        zone = "monitoring.srv.ftsell.de"
        vars.notification_telegram_token = "{{ monitoring_telegram_bot_token }}"
        vars.notification_chat_id = "$user.vars.telegram_id$"
      }
     
      apply Notification "host-down" to Host {
        import "telegram-notification"
        types = ["Custom", "Problem", "Recovery"]
        users = [ "ftsell" ]
        {% raw -%}
        vars.notification_text = {{
          notification_type = macro("$notification.type$")
          notification_comment = macro("$notification.comment$")
          if (notification_type == "CUSTOM") {
            return "*$host.display_name$*: $notification.comment$"
          } else if (notification_type == "PROBLEM" || notification_type == "RECOVERY") {
            text = "*$notification_type$: $host.display_name$ is $host.state$*"
            if (notification_comment) {
              text += "\n\n_Comment_: $notification.comment$"
            }
            text += "\n\n_Last Check (at $host.last_check$)_: `$host.output$`"
            return text
          } else {
            return "Notification of unknon type $notification_type$ was just triggered"
          }
        }}
        {% endraw -%}
        assign where host.enable_notifications
      }

      apply Notification "service-down" to Service {
        import "telegram-notification"
        types = ["Custom", "Problem", "Recovery"]
        states = ["OK", "Critical"]
        users = ["ftsell"]
        {% raw -%}
        vars.notification_text = {{
          notification_type = macro("$notification.type$")
          notification_comment = macro("$notification.comment$")
          if (notification_type == "CUSTOM") {
            return "*$service.display_name$ on $host.display_name$*: $notification.comment$"
          } else if (notification_type == "PROBLEM" || notification_type == "RECOVERY") {
            text = "*$notification_type$: $service.display_name$ on $host.display_name$ is $service.state$*"
            if (notification_comment) {
              text += "\n\n_Comment_: $notification.comment$"
            }
            text += "\n\nLast Check (at $service.last_check$): `$service.output$`"
            return text
          } else {
            return "Notification of unknown type $notification_type$ was just triggered"
          }
        }}
        {%endraw -%}
        assign where service.enable_notifications
      }

  monitoring.srv.ftsell.de:
    hosts.conf: |
      object Host "monitoring.srv.ftsell.de" {
        import "generic-host"
        import "normal-server"
        address = "monitoring.srv.ftsell.de"
        display_name = "Monitoring"

        vars.websites = [
          "monitoring.ftsell.de",
        ]
      }

      object Host "main.svc.ftsell.de" {
        import "virtual-host"
        address = "main.svc.ftsell.de"
        display_name = "K8S Main"

        vars.websites = [
          "ftsell.de",
          "cloud.ftsell.de",
          "git.ftsell.de",
          "budget.ftsell.de",
          "todo.ftsell.de",
          "kino.timonengelke.de",
          "time.ftsell.de",
          "argocd.ftsell.de",
          "auth.ftsell.de",
        ]
      }

      object Host "mail.svc.ftsell.de" {
        import "virtual-host"
        address = "mail.svc.ftsell.de"
        display_name = "K8S Mail"

        vars.imap_check_enabled = true
        vars.smtp_check_enabled = true
        vars.submission_check_enabled = true
      }

    services.conf: |
      object Service "icingadb" {
        import "generic-service"
        host_name = "monitoring.srv.ftsell.de"
        check_command = "icingadb"
      }

      object Service "icinga-cluster" {
        import "generic-service"
        check_command = "cluster"
        host_name = "monitoring.srv.ftsell.de"
      }

  main.srv.ftsell.de:
    host.conf: |
      object Host "main.srv.ftsell.de" {
        import "generic-host"
        import "normal-server"
        address = "main.srv.ftsell.de"
        display_name = "Main Server"
      }

  vpn.srv.ftsell.de:
    host.conf: |
      object Host "vpn.srv.ftsell.de" {
        import "generic-host"
        import "normal-server"
        address = "vpn.srv.ftsell.de"
        display_name = "VPN Server"
      }

      object Host "nas.vpn.private" {
        import "generic-host"
        address = "10.20.30.103"
        address6 = "fc10:20:30::103"
        display_name = "NAS (vpn)"

        vars.ssh_check_enabled = true
        vars.ssh_check_notify = true
      }
      object Dependency "vpn-nas2home-nas" {
        child_host_name = "nas.vpn.private"
        parent_host_name = "nas.home.ftsell.de"
      }

  nas.home.ftsell.de:
    host.conf: |
      object Host "nas.home.ftsell.de" {
        import "generic-host"
        address = "nas.home.ftsell.de"
        display_name = "NAS (public)"

        vars.apt_check_enabled = true
        vars.apt_check_notify = false
        vars.systemd_check_enabled = true
        vars.systemd_check_notify = true
        vars.running_kernel_check_enabled = true
        vars.running_kernel_notify = false

        vars.websites = [
          "ha.home.ftsell.de",
          "media.home.ftsell.de",
          "audiobooks.home.ftsell.de",
        ]
      }
