apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: samba-csi-driver

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.10.0/deploy/rbac-csi-smb.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.10.0/deploy/csi-smb-driver.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.10.0/deploy/csi-smb-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/v1.10.0/deploy/csi-smb-node.yaml
  - storage-class.yml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: smbcreds
    envs:
      - credentials.secret.env
