apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: mediamtx
      labels: &labels
        app.kubernetes.io/name: mediamtx
        app.kubernetes.io/component: streaming-server
    spec:
      selector: *labels
      ports:
        - name: http
          port: 8888
          targetPort: http
        - name: rtmp
          port: 1935
          targetPort: rtmp

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mediamtx
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          containers:
            - name: mediamtx
              image: docker.io/bluenviron/mediamtx:latest-ffmpeg
              imagePullPolicy: Always
              env:
                - name: MTX_WEBRTC
                  value: "no"
                - name: MTX_RTSP
                  value: "no"
                - name: MTX_RTMP
                  value: "yes"
                - name: MTX_HLS
                  value: "yes"
                - name: MTX_SRT
                  value: "no"
              ports:
                - name: http
                  containerPort: 8888
                - name: rtmp
                  containerPort: 1935
