---
apiVersion: v1
kind: Service
metadata:
  name: pixelflut-intern
  labels: &labels
    app.kubernetes.io/name: pixelflut
    app.kubernetes.io/component: pixelflut-server
spec:
  selector: *labels
  ports:
    - name: tcp
      port: 9876
      targetPort: tcp
    - name: udp
      port: 9876
      targetPort: udp
      protocol: UDP
    - name: websocket
      port: 9875
      targetPort: websocket



---
apiVersion: v1
kind: Service
metadata:
  name: pixelflut-lb
  labels: &labels
    app.kubernetes.io/name: pixelflut
    app.kubernetes.io/component: pixelflut-server
  annotations:
    metallb.universe.tf/allow-shared-ip: main-sharing-key
    metallb.universe.tf/ip-allocated-from-pool: main
spec:
  selector: *labels
  type: LoadBalancer
  ports:
    - name: tcp
      port: 9876
      targetPort: tcp
    - name: udp
      port: 9876
      targetPort: udp
      protocol: UDP
