- name: Install packages I usually want
  become: true
  apt:
    name:
      - git
      - git-crypt
      - git-lfs
      - gpg
      - htop
      - iftop
      - iotop
      - openssh-client
      - tmux
      - zsh

- name: Create user account with correct data
  become: true
  register: user_account
  user:
    name: ftsell
    shell: "{{ ftsell_shell }}"
    comment: "{{ ftsell_gecos }}"

- name: Ensure authorized ssh key is present
  authorized_key:
    user: ftsell
    comment: ftsell
    exclusive: true
    key: "{{ lookup('file', '../../terraform/resources/id_rsa.pub') }}"

- name: Setup my dotfiles repo
  block:
    - name: Stat .git directory
      register: git_stat
      failed_when: not git_stat.stat.exists
      stat:
        path: .git
    - name: Pull newest dotfiles content
      ignore_errors: true
      git:
        repo: https://git.ftsell.de/ftsell/dotfiles.git
        dest: "~"

  rescue:
    - name: Clone and checkout my dotfiles repo
      ignore_errors: true
      shell: |
        git clone https://git.ftsell.de/ftsell/dotfiles.git dotfiles
        mv dotfiles/.git ./
        rm -rf dotfiles
        git checkout .
        git submodule update --init --recursive
