# {{ ansible_managed }}

# See https://grafana.com/docs/loki/latest/clients/promtail/configuration/

server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /srv/promtail/positions.yml
clients:
  - url: http://localhost:3100/loki/api/v1/push
scrape_configs:
  # collect logs from /var/log
  - job_name: var_log
    static_configs:
      - labels:
          host: monitoring
          __path__: /var/log/auth.log
      - labels:
          host: monitoring
          __path__: /var/log/aptitude

  # collect logs from systemd-journald
  - job_name: systemd
    journal:
      max_age: 1h
      path: /var/log/journal
      labels:
        host: monitoring
    relabel_configs:
      # only keep .service logs
      - action: keep
        source_labels: [ __journal__systemd_unit ]
        regex: (.+)\.service
      # keep unit and priority labels
      - source_labels: [ __journal__systemd_unit ]
        target_label: systemd_unit
      - source_labels: [ __journal_priority_keyword ]
        target_label: systemd_priority

