# {{ ansible_managed }}

# See https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 30s

scrape_configs:

  ###
  # Main Config
  #
  - job_name: local-services
    static_configs:
      - targets: [ localhost:9100 ]
        labels:
          instance: monitoring
      - targets: [ localhost:3100 ]
        labels:
          instance: loki

  - job_name: ping4
    metrics_path: /probe
    static_configs:
      - targets: &ping_targets {{ monitored_icmp_targets | mandatory | to_yaml }}
    params:
      module: [ icmp4 ]
    relabel_configs: &blackbox_relabel_config
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: http4
    metrics_path: /probe
    static_configs:
      - targets: &http_targets {{ monitored_http_targets | mandatory | to_yaml }}
    params:
      module: [ http4 ]
    relabel_configs: *blackbox_relabel_config

  - job_name: smtp4
    metrics_path: /probe
    static_configs:
      - targets: &smtp_targets {{ monitored_smtp_targets | mandatory | to_yaml }}
    params:
      module: [ smtp4 ]
    relabel_configs: *blackbox_relabel_config

  - job_name: imap4
    metrics_path: /probe
    static_configs:
      - targets: &imap_targets {{ monitored_imap_targets | mandatory | to_yaml }}
    params:
      module: [ tls_connect4 ]
    relabel_configs: *blackbox_relabel_config

  ###
  # Config repetitions for IPv6
  #
  - job_name: ping6
    metrics_path: /probe
    static_configs:
      - targets: *ping_targets
    params:
      module: [ icmp6 ]
    relabel_configs: *blackbox_relabel_config

  - job_name: http6
    metrics_path: /probe
    static_configs:
      - targets: *http_targets
    params:
      module: [ http6 ]
    relabel_configs: *blackbox_relabel_config

  - job_name: smtp6
    metrics_path: /probe
    static_configs:
      - targets: *smtp_targets
    params:
      module: [ smtp4 ]
    relabel_configs: *blackbox_relabel_config

  - job_name: imap6
    metrics_path: /probe
    static_configs:
      - targets: *imap_targets
    params:
      module: [ tls_connect6 ]
    relabel_configs: *blackbox_relabel_config
