# This is an ansible playbook which retrieves credentials so that the cluster can be accessed

# See the kubernetes documentation on how authentication works:
#   https://kubernetes.io/docs/reference/access-authn-authz/authentication/

- hosts: kube_control_plane[0]
  vars_prompt:
    - name: k8s_username
      prompt: Kubernetes Username (this can be arbitrary but should identify you)
      private: false
    - name: k8s_group
      prompt: Kubernetes Group (system:masters is basically root)
      private: false
      default: system:masters

  tasks:
    - name: assert entered variables have valid values
      with_items: [ k8s_username, k8s_group ]
      become: true
      assert:
        that: "{{ item }} != ''"
        fail_msg: entered {{ item }} is invalid
        quiet: true

    - name: create private key for {{ k8s_username }}
      become: true
      community.crypto.openssl_privatekey:
        path: /etc/kubernetes/ssl/user-{{ k8s_username | trim }}.key

    - name: create csr for {{ k8s_username }}
      become: true
      community.crypto.openssl_csr:
        path: /etc/kubernetes/ssl/user-{{ k8s_username | trim }}.csr
        privatekey_path: /etc/kubernetes/ssl/user-{{ k8s_username | trim }}.key
        common_name: "{{ k8s_username | trim }}"
        organization_name: "{{ k8s_group | trim }}"

    - name: create certificate for {{ k8s_username }}
      become: true
      community.crypto.x509_certificate:
        path: /etc/kubernetes/ssl/user-{{ k8s_username | trim }}.crt
        csr_path: /etc/kubernetes/ssl/user-{{ k8s_username | trim }}.csr
        provider: ownca
        ownca_path: /etc/kubernetes/ssl/ca.crt
        ownca_privatekey_path: /etc/kubernetes/ssl/ca.key

    - name: fetch key material
      become: true
      with_items:
        - "user-{{ k8s_username | trim }}.key"
        - "user-{{ k8s_username | trim }}.crt"
        - ca.crt
      fetch:
        src: /etc/kubernetes/ssl/{{ item }}
        dest: "~/{{ item }}"
        flat: true

    - debug:
        msg:
          - Key material has been placed as ~/user-{{ k8s_username | trim }}.key, ~/user-{{ k8s_username | trim }}.crt and ~/ca.crt
          - See this folders README.md on how to integrate it into your kubectl config
