# This playbook configures all server that are always reachable via the internet

- hosts: hcloud
  roles:
    - linux_base
    - ssh_server
    - user_accounts

- hosts: hcloud
  roles:
    - role: icinga_node
      when: icinga_node_cluster_root == "self"
    - role: icinga_node
      when: icinga_node_cluster_root != "self"

- hosts: vpn
  roles:
    - vpn_server
