# This playbook configures all server that are always reachable via the internet

- hosts: hcloud
  roles:
    - linux_base
    - ssh_server
    - user_accounts

- hosts: monitoring
  roles:
    - monitoring_server

- hosts: vpn
  roles:
    - vpn_server
