# router networking needs to be configured before everything else so that the other hosts have internet connectivity
- hosts: router
  roles:
    - linux_base
    - router
    - user_accounts

- hosts: all,!router
  roles:
    - linux_base
    - user_accounts
