- hosts: hcloud,!bastion
  tasks:
    - name: shutdown protected servers
      become: true
      shutdown: {}

- hosts: bastion
  tasks:
    - name: shutdown bastion
      become: true
      shutdown: {}
