- hosts: all
  gather_facts: false
  tasks:
    - name: perform system update & safe upgrade
      become: true
      apt:
        update_cache: true
        upgrade: safe
        autoremove: true
        autoclean: true
