apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bene-timetracker
commonLabels:
  app.kubernetes.io/part-of: bene-timetracker

resources:
  - manifests/namespace.yml
  - manifests/ingress.yml
  - manifests/deployment.yml
  - manifests/service.yml
  - manifests/storage.yml

secretGenerator:
  - name: bene-timetracker
    envs:
      - config.secret.env
