apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels: &labels
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: webserver
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:

      volumes:
        - name: secrets
          secret:
            secretName: keycloak
        - name: custom-providers
          emptyDir: {}

      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak
          imagePullPolicy: Always
          args: [ "start" ]
          envFrom:
            - configMapRef:
                name: keycloak
            - secretRef:
                name: keycloak
          ports:
            - name: http
              containerPort: 8080
            - name: mgmt
              containerPort: 9000
          volumeMounts:
            - name: secrets
              mountPath: "/opt/jboss/secrets"
            - name: custom-providers
              mountPath: "/opt/keycloak/providers"
          readinessProbe:
            httpGet:
              port: mgmt
              path: /health/ready
          resources:
            requests:
              cpu: "0.1"
              memory: "2G"
            limits:
              memory: "2G"

      initContainers:
        - name: install-restrict-client-auth
          image: quay.io/curl/curl
          volumeMounts:
            - name: custom-providers
              mountPath: "/opt/keycloak/providers"
          command: [ "sh", "-c" ]
          securityContext:
            runAsUser: 1000
            runAsGroup: 1
          args:
            - |
              set -x
              curl -sSL https://github.com/sventorben/keycloak-restrict-client-auth/releases/download/v26.0.0/keycloak-restrict-client-auth.jar -o /opt/keycloak/providers/keycloak-restrict-client-auth-26.0.0.jar
