---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/kubernetes-dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actual-budget
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/actual-budget
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/keycloak
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mailserver
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  interval: 1m0s
  path: ./k8s/apps/mailserver
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: http-whoami
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/http-whoami
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/homepage
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: memos
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/memos
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/nextcloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
