---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/kubernetes-dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actual-budget
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/actual-budget
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
