---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: finnfrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/ftsell/finnfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/base-system/fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/base-system/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: finnfrastructure
