apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./flux-install.yml
  - ./cd-base-system.yml
  - ./cd-apps.yml

secretGenerator:
  - name: sops-keys
    namespace: flux-system
    options:
      disableNameSuffixHash: true
    files:
      - "identity.agekey=fluxcd.secret.agekey"
