- name: reload caddy
  tags: [monitoring, monitoring_server, icinga_node, webserver, caddy]
  become: true
  ansible.builtin.systemd:
    name: caddy.service
    state: reloaded

- name: restart icingadb
  tags: [monitoring, monitoring_server, icinga_node, icinga, icinga2, icingadb]
  become: true
  ansible.builtin.systemd:
    name: icingadb.service
    state: restarted

- name: Restart icinga2
  tags: [monitoring, monitoring_server, icinga_node, icinga, icinga2, icinga_zone, icinga_zones]
  become: true
  ansible.builtin.systemd:
    name: icinga2.service
    state: restarted
