- name: Setup icinga web
  tags: [icingaweb, web]
  block:

    - name: Install icingaweb2
      become: true
      ansible.builtin.apt:
        # mini-http is not actually used but the package requires a webserver and caddy does not satisfy that constraint formally
        name: [icingacli, icingaweb2, php-imagick, icingadb-web, mini-httpd]

    - name: Create postgresql user for icingaweb2
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: icingaweb2
        password: icingaweb2

    - name: Create postgresql database for icingaweb2
      become: true
      become_user: postgres
      register: create_db
      community.postgresql.postgresql_db:
        name: icingaweb2
        owner: icingaweb2

    - name: Configure icingaweb2
      become: true
      with_items:
        - config.ini
        - authentication.ini
        - groups.ini
        - resources.ini
        - roles.ini
        - modules/icingadb/config.ini
        - modules/icingadb/redis.ini
        - modules/icingadb/commandtransports.ini
      ansible.builtin.template:
        src: icingaweb2/{{ item }}
        dest: /etc/icingaweb2/{{ item }}
        owner: www-data
        group: icingaweb2
        mode: u=rw,g=rw,o=

    - name: Enable icingaweb2 modules
      become: true
      with_items:
        - doc
        - icingadb
      ansible.builtin.file:
        path: /etc/icingaweb2/enabledModules/{{ item }}
        state: link
        src: /usr/share/icingaweb2/modules/{{ item }}
        owner: www-data
        group: icingaweb2
