- tags: [ prometheus, node-exporter, node_exporter ]
  block:
    - name: configure node-exporter systemd unit
      become: true
      notify: restart node-exporter
      template:
        src: node-exporter.service
        dest: /etc/systemd/system/node-exporter.service
        mode: u=rw,g=r,a=r

    - name: ensure node-exporter is running and enabled
      become: true
      systemd:
        name: node-exporter.service
        state: started
        enabled: true
        daemon_reload: true
