- tags: [ webserver, caddy ]
  block:
    - name: setup caddy apt key
      become: true
      apt_key:
        id: 65760C51EDEA2017CEA2CA15155B6D79CA56EA34
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

    - name: setup caddy apt repository
      become: true
      get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
        dest: /etc/apt/sources.list.d/caddy-stable.list

    - name: install caddy
      become: true
      apt:
        name: caddy
        update_cache: true

    - name: configure caddy
      become: true
      notify: reload caddy
      template:
        src: Caddyfile
        dest: /etc/caddy/Caddyfile
