- tags: [ grafana ]
  block:
    - name: create grafana config directory
      become: true
      file:
        path: /etc/grafana
        state: directory

    - name: create grafana state directory
      become: true
      file:
        path: /srv/grafana
        state: directory
        mode: u=rwX,g=rwX,o=rwX
        owner: nobody
        group: nogroup

    - name: configure grafana
      become: true
      notify: restart grafana
      template:
        src: grafana.ini
        dest: /etc/grafana/grafana.ini

    - name: configure grafana systemd unit
      become: true
      notify: restart grafana
      template:
        src: grafana.service
        dest: /etc/systemd/system/grafana.service
        mode: u=rw,g=r,a=r

    - name: ensure grafana is running and enabled
      become: true
      systemd:
        name: grafana.service
        state: started
        enabled: true
        daemon_reload: true
