- name: Install icingadb packages
  tags: [redis]
  become: true
  ansible.builtin.apt:
    # psycopg2 is required for the ansible modules to work
    name: [icingadb, icingadb-redis, postgresql, python3-psycopg2]

- name: Create postgresql user for icingadb
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: icingadb
    password: icingadb

- name: Create postgresql database for icingadb
  become: true
  become_user: postgres
  register: create_db
  community.postgresql.postgresql_db:
    name: icingadb
    owner: icingadb

- name: Add citext extension to icingadb postgresql database
  become: true
  become_user: postgres
  community.postgresql.postgresql_ext:
    db: icingadb
    ext: citext

- name: Import icingadb schema into postgresql database
  when: create_db.changed
  community.postgresql.postgresql_script:
    host: localhost
    db: icingadb
    login_user: icingadb
    login_password: icingadb
    path: /usr/share/icingadb/schema/pgsql/schema.sql

- name: Configure icingadb daemon
  become: true
  notify: restart icingadb
  ansible.builtin.template:
    src: icingadb.yml
    dest: /etc/icingadb/config.yml
    owner: icingadb
    group: root
    mode: u=rw,g=r,o=

- name: Ensure services are enabled and started
  tags: [systemd]
  become: true
  with_items:
    - icingadb-redis.service
    - postgresql.service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true

- name: Enable icinga2 icingadb feature
  become: true
  notify: Restart icinga2
  ansible.builtin.file:
    path: /etc/icinga2/features-enabled/icingadb.conf
    state: link
    src: /etc/icinga2/features-available/icingadb.conf
    owner: nagios
    group: nagios
