- tags: [ prometheus, blackbox-exporter, blackbox_exporter ]
  block:
    - name: create blackbox-exporter config directory
      become: true
      file:
        path: /etc/blackbox-exporter
        state: directory

    - name: configure blackbox-exporter
      become: true
      notify: restart blackbox-exporter
      template:
        src: blackbox-exporter.yml
        dest: /etc/blackbox-exporter/config.yml

    - name: configure blackbox-exporter systemd unit
      become: true
      notify: restart blackbox-exporter
      template:
        src: blackbox-exporter.service
        dest: /etc/systemd/system/blackbox-exporter.service
        mode: u=rw,g=r,a=r

    - name: ensure blackbox-exporter is running and enabled
      become: true
      systemd:
        name: blackbox-exporter.service
        state: started
        enabled: true
        daemon_reload: true
