---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus:discovery
subjects:
  - kind: ServiceAccount
    name: promtail
