apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage
commonLabels:
  app.kubernetes.io/part-of: local-path-provisioner

resources:
  - https://github.com/rancher/local-path-provisioner//deploy?ref=v0.0.30

patches:
  - target:
      group: storage.k8s.io
      version: v1
      kind: StorageClass
      name: local-path
    path: storageclass.patch.yml

configMapGenerator:
  - name: local-path-config
    namespace: local-path-storage
    behavior: merge
    files:
      - "config.json=config.json"
