apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: referral-code-randomizer
namespace: referral-code-randomizer

resources:
  - namespace.yml
  - cronjob.yml

configMapGenerator:
  - name: script
    files:
      - script.py
