- tags: [ wireguard]
  block:
    - name: install wireguard userland tools
      become: true
      package:
        name: wireguard-tools

    - name: create wireguard config directories
      become: true
      file:
        path: /etc/wireguard
        state: directory

    - name: write wireguard interface config
      become: true
      notify: reconfigure wg_vpn interface
      template:
        src: wg_vpn.conf
        dest: /etc/wireguard/wg_vpn.conf

    - name: ensure wireguard interface is configured and up
      become: true
      systemd:
        name: wg-quick@wg_vpn.service
        state: started
        enabled: true
