- tags: [ bind9, named, dns_server, dns-server ]
  block:
    - name: install bind9 name server
      become: true
      package:
        name: bind9

    - name: configure bind9 name server
      become: true
      notify: reload bind9 name server
      with_fileglob: templates/bind/*
      loop_control:
        label: "{{ item | basename }}"
      template:
        src: "{{ item }}"
        dest: /etc/bind/{{ item | basename }}
        validate: >-
          {% if "db" in item %}
          named-checkzone test %s
          {% else %}
          named-checkconf %s
          {% endif %}

    - name: ensure bind9 name server is running and enabled
      become: true
      systemd:
        name: named.service
        state: started
        enabled: true
