- tags: [ nftables, firewall ]
  block:
    - name: configure linux ip forwarding
      become: true
      with_items:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding
      sysctl:
        name: "{{ item }}"
        value: "1"
        sysctl_set: true

    - name: install nftables
      become: true
      package:
        name: nftables

    - name: configure nftables rules
      become: true
      notify: reload nftables
      template:
        src: nftables.conf
        dest: /etc/nftables.conf
        validate: nft -c -f %s

    - name: ensure nftables rules are loaded now and at system startup
      become: true
      systemd:
        name: nftables.service
        state: started
        enabled: true
