apiVersion: v1
kind: List
items:

  #
  # Service
  #
  - apiVersion: v1
    kind: Service
    metadata:
      name: vikunja-api
      labels: &labels
        app.kubernetes.io/name: vikunja-api
        app.kubernetes.io/component: api-server
    spec:
      selector: *labels
      ports:
        - port: 3456
          name: http
          targetPort: http



  #
  # Storage
  #
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: vikunja-files
    spec:
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1G



  #
  # Deployment
  #
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vikunja-api
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          volumes:
            - name: config
              configMap:
                name: vikunja-api
            - name: files
              persistentVolumeClaim:
                claimName: vikunja-files
          containers:
            - name: vikunja-api
              image: docker.io/vikunja/api
              imagePullPolicy: Always
              volumeMounts:
                - name: config
                  mountPath: /app/vikunja/config.yml
                  subPath: config.yml
                - name: files
                  mountPath: /app/vikunja/files
              ports:
                - name: http
                  containerPort: 3456
              readinessProbe:
                httpGet:
                  port: http
                  path: /health
