apiVersion: v1
kind: List
items:

  #
  # Service
  #
  - apiVersion: v1
    kind: Service
    metadata:
      name: vikunja-frontend
      labels: &labels
        app.kubernetes.io/name: vikunja-frontend
        app.kubernetes.io/component: frontend
    spec:
      selector: *labels
      ports:
        - port: 80
          name: http
          targetPort: http



  #
  # Deployment
  #
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vikunja-frontend
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          containers:
            - name: vikunja-api
              image: docker.io/vikunja/frontend
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 80
              readinessProbe:
                httpGet:
                  port: http
                  path: /health
