apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
commonLabels:
  app.kubernetes.io/part-of: gitea

resources:
  - manifests/gitea-deployment.yml
  - manifests/gitea-storage.yml
  - manifests/gitea-service.yml
  - manifests/gitea-ssh-service.yml
  - manifests/namespace.yml
  - manifests/ingress.yml

images:
  - name: docker.io/gitea/gitea
    newTag: "1.21.1"

configMapGenerator:
  - name: gitea
    envs:
      - config.env

secretGenerator:
  - name: gitea
    envs:
      - secret.env
