- tags: [ qcow, qcow-image ]
  block:
    - name: install qemu-utils
      become: true
      apt:
        name: qemu-utils

    - name: configure nbd kernel module to load at boot
      become: true
      lineinfile:
        path: /etc/modules
        regexp: "^nbd$"
        line: nbd

    - name: load nbd kernel module now
      become: true
      modprobe:
        name: nbd

    - name: deploy nbc-connect systemd service config
      become: true
      register: service_config
      template:
        src: storage-box-qcow.service
        dest: /etc/systemd/system/storage-box-qcow.service

    - name: start nbc-connect systemd unit
      become: true
      systemd:
        name: storage-box-qcow.service
        state: started
        daemon_reload: "{{ service_config.changed }}"

    - name: configure fstab for automounting the qcow image
      become: true
      mount:
        path: /srv/storage-box-virt/
        src: /dev/nbd0p1
        fstype: ext4
        state: mounted
        opts: x-systemd.requires=storage-box-qcow.service

    - name: confige storage-box-virt permissions
      become: true
      file:
        path: /srv/storage-box-virt/
        state: directory
        owner: storage-box
        group: storage-box
        mode: u=rwXs,g=rwXs,o=rwXs
