- tags: [ swap ]
  block:
    - name: configure linux swappiness
      become: true
      sysctl:
        name: vm.swappiness
        value: 40
        sysctl_set: true

    - name: check for swap file existence
      ignore_errors: true
      register: swap_stat
      stat:
        path: /swapfile

    - name: setup swap file
      when: not swap_stat.stat.exists
      become: true
      block:
        - name: create swapfile
          command: "fallocate -l {{ swap_size }} /swapfile"
        - name: make swapfile a valid swap target
          command: "mkswap /swapfile"
        - name: set swapfile permissions
          file:
            path: /swapfile
            state: file
            mode: 600
        - name: enable swapfile
          command: "swapon /swapfile"

    - name: setup swap mounting
      become: true
      ansible.posix.mount:
        src: /swapfile
        path: swap
        fstype: swap
        opts: defaults
        state: present
