- tags: [ storage-box, shared-storage-mount, k8s ]
  block:
    - name: create local storage group
      become: true
      group:
        name: storage-box
        gid: 2000

    - name: create local storage user
      become: true
      user:
        name: storage-box
        uid: 2000
        group: storage-box
        home: /opt/k8s/storage-box
        create_home: false
        password_lock: true
        shell: /usr/sbin/nologin

    - name: install cifs
      become: true
      apt:
        name: cifs-utils

    - name: configure fstab entry for auto-mounting storage box via samba
      become: true
      ansible.posix.mount:
        src: //u343701.your-storagebox.de/u343701-sub1
        path: /srv/storage-box/
        fstype: smb3
        opts: iocharset=utf8,rw,uid=2000,gid=2000,file_mode=06666,dir_mode=06777,user={{ storage_box_k8s_user | mandatory }},pass={{ storage_box_k8s_pass | mandatory }},cache=none,vers=default
        state: mounted
