- name: Create PKI
  tags: [pki]
  block:
    - name: Create required pki directories
      become: true
      with_items:
        - { path: /var/lib/icinga2/ca, mode: "u=rwx,g=,o=" }
        - { path: /var/lib/icinga2/certs, mode: "u=rwx,g=rx,o=" }
      file:
        path: "{{ item.path }}"
        state: directory
        owner: nagios
        group: nagios
        mode: "{{ item.mode }}"
    - name: Create ca private key
      become: true
      ansible.builtin.openssl_privatekey:
        path: /var/lib/icinga2/ca/ca.key
        owner: nagios
        group: nagios
        mode: u=rw,g=r,o=
    - name: Create ca csr
      become: true
      ansible.builtin.openssl_csr:
        path: /var/lib/icinga2/ca.csr
        privatekey_path: /var/lib/icinga2/ca/ca.key
        common_name: Icinga CA
        basic_constraints:
          - "CA:TRUE"
        basic_constraints_critical: true
        owner: nagios
        group: nagios
        mode: u=rw,g=r,o=
    - name: Create self-signed ca certificate
      become: true
      ansible.builtin.openssl_certificate:
        path: /var/lib/icinga2/ca/ca.crt
        csr_path: /var/lib/icinga2/ca.csr
        privatekey_path: /var/lib/icinga2/ca/ca.key
        provider: selfsigned
        owner: nagios
        group: nagios
        mode: u=rw,g=r,o=
    - name: Copy CA certificate to cert dir
      become: true
      ansible.builtin.copy:
        src: /var/lib/icinga2/ca/ca.crt
        dest: /var/lib/icinga2/certs/ca.crt
        remote_src: true
        owner: nagios
        group: nagios
        mode: u=rw,g=r,o=
