apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: prometheus
resources:
  - manifests/deployment.yml
  - manifests/service.yml
  - manifests/rbac.yml

configMapGenerator:
  - name: prometheus
    files:
      - config/prometheus.yml

secretGenerator:
  - name: prometheus
    files:
      - remote_access.passwd.txt=config/remote_access.passwd.secret.txt
