apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-mail.ftsell.de
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http
  secretName: tls-mail.ftsell.de
  dnsNames:
    - "mail.ftsell.de"
    - "mail.srv.ftsell.de"
    - "rspamd.mail.ftsell.de"
