apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailserver
spec:
  tls:
    - secretName: tls-mail.ftsell.de
      hosts:
        - rspamd.mail.ftsell.de
  rules:
    - host: rspamd.mail.ftsell.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailserver
                port:
                  name: rspamd-admin
