apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1g
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - secretName: tls-git.lly.sh
      hosts:
        - git.lly.sh
  rules:
    - host: git.lly.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgejo
                port:
                  name: http
