apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rom-o-mat
commonLabels:
  app.kubernetes.io/part-of: rom-o-mat
commonAnnotations:
  ftsell.de/app-owner: Kalliope Theater AG

resources:
  - manifests/namespace.yml
  - manifests/deployment.yml
  - manifests/service.yml
  - manifests/ingress.yml
