- vars:
    peer_i: "{{ ansible_loop.index }}"
    peer_private_address: "{{ hostvars[peer].private_ipv4 }}"
    peer_public_address: "{{ hostvars[peer].public_ipv4 }}"
  block:
  - name: Configure virtual tunnel devices
    become: true
    notify: reload systemd-networkd
    template:
      src: overlay.netdev
      dest: /etc/systemd/network/30-ensOvl{{ peer_i }}.netdev
      mode: u=rw,g=r,o=
      owner: systemd-network
      group: systemd-network
