apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: metallb

resources:
  - github.com/metallb/metallb/config/native?ref=v0.13.9
  - address_pools.yml
#  - bgp.yml
