apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-mail.ftsell.de
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  secretName: tls-mail.ftsell.de
  dnsNames:
    - "mail.ftsell.de"
    - "*.mail.ftsell.de"
