vpn_iface: wg_vpn
vpn_server_endpoint: vpn.ftsell.de:51820
vpn_server_pub_key: "{{ hostvars['vpn'].wg_pub_key }}"
vpn_server_ips:
  - "10.20.30.0/24"
  - "fc10:20:30::0/64"
vpn_dns_servers:
  - 10.20.30.2
  - fc10:20:30::2
