- tags: [ networking, systemd, systemd-networkd, systemd_networkd ]
  block:
    - name: Remove unwanted networking tools
      become: true
      apt:
        state: absent
        purge: true
        name:
          - isc-dhcp-client
          - resolvconf

    - name: Disable and stop unwanted systemd services
      become: true
      with_items:
        - hc-net-scan.service
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false

    - name: Disable cloud-init based network configuration
      become: true
      template:
        src: cloud-init-disable-network.yml
        dest: /etc/cloud/cloud.cfg.d/95-disable-network-config.cfg

    - name: Remove existing cloud-init based network device config
      become: true
      file:
        path: /etc/network/interfaces.d/50-cloud-init
        state: absent

    - name: Start and enable wanted systemd services
      become: true
      with_items:
        - systemd-networkd.service
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true

    - name: Configure networking via systemd-networkd
      become: true
      notify: reload systemd-networkd
      with_items: "{{ systemd_networkd_configs | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      vars:
        file_content: "{{ item.value }}"
      template:
        src: systemd-file-template
        dest: /etc/systemd/network/{{ item.key }}
        mode: u=rw,g=r,o=
        owner: systemd-network
        group: systemd-network

    - name: Configure DNS Servers
      become: true
      with_items:
        - { server: 185.12.64.1, state: present }
        - { server: 2a01:4ff:ff00::add:1, state: absent }
        - { server: 2a01:4ff:ff00::add:2, state: absent}
      lineinfile:
        path: /etc/resolv.conf
        regexp: "^nameserver {{ item.server }}$"
        line: "nameserver {{ item.server }}"
        state: "{{ item.state }}"

    - name: Flush Handlers
      meta: flush_handlers
