- tags: [ liunux_base, base, linux, apt, unattended-upgrades ]
  block:
    - name: install unattended-upgrades
      become: true
      apt:
        name: [ unattended-upgrades, apt-listchanges ]

    - name: enable periodic automated upgrades
      become: true
      debconf:
        name: unattended-upgrades
        setting: unattended-upgrades/enable_auto_updates
        vtype: boolean
        value: "true"
