- tags: [ linux_base, base, linux ]
  block:
    - name: Verify expected linux distribution
      assert:
        that:
          - "ansible_distribution | lower == expected_dist | lower"
          - "ansible_distribution_version == expected_dist_version | string"

    - import_tasks: configure_networking.yml

    - name: Install some base packages
      become: true
      apt:
        update_cache: true
        name:
          - git
          - git-crypt
          - gpg
          - vim

    - import_tasks: configure_locale.yml
    - import_tasks: set_hostname.yml
